#' ----
#' Title: Generalized linear models
#' Author: Kelli Faye Johnson
#' Date: 2016-04-27
#' ----

###############################################################################
###############################################################################
#' Binomial glm
###############################################################################
###############################################################################
modbin <- list()
modbin[[1]] <- glm(y ~ portgrp,
  family = "quasibinomial", data = data.binom)
modbin[[length(modbin) + 1]] <- update(modbin[[1]], ~ . + Number.of.vessels)
modbin[[length(modbin) + 1]] <- update(modbin[[1]], ~ . + Crew)
modbin[[length(modbin) + 1]] <- update(modbin[[1]], ~ . + Fuel)
modbin[[length(modbin) + 1]] <- update(modbin[[1]], ~ . + HorsePower)
modbin[[length(modbin) + 1]] <- update(modbin[[1]], ~ . + FuelCapacity)
modbin[[length(modbin) + 1]] <- update(modbin[[1]], ~ . + Length)
modbin[[length(modbin) + 1]] <- update(modbin[[1]], ~ . + Fixed.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[1]], ~ . + Variable.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[1]], ~ . + sablefish)
modbin[[length(modbin) + 1]] <- update(modbin[[2]], ~ . + Crew)
modbin[[length(modbin) + 1]] <- update(modbin[[2]], ~ . + Fuel)
modbin[[length(modbin) + 1]] <- update(modbin[[2]], ~ . + HorsePower)
modbin[[length(modbin) + 1]] <- update(modbin[[2]], ~ . + FuelCapacity)
modbin[[length(modbin) + 1]] <- update(modbin[[2]], ~ . + Length)
modbin[[length(modbin) + 1]] <- update(modbin[[2]], ~ . + Fixed.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[2]], ~ . + Variable.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[2]], ~ . + sablefish)
modbin[[length(modbin) + 1]] <- update(modbin[[3]], ~ . + Number.of.vessels)
modbin[[length(modbin) + 1]] <- update(modbin[[3]], ~ . + Fuel)
modbin[[length(modbin) + 1]] <- update(modbin[[3]], ~ . + HorsePower)
modbin[[length(modbin) + 1]] <- update(modbin[[3]], ~ . + FuelCapacity)
modbin[[length(modbin) + 1]] <- update(modbin[[3]], ~ . + Length)
modbin[[length(modbin) + 1]] <- update(modbin[[3]], ~ . + Fixed.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[3]], ~ . + Variable.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[3]], ~ . + sablefish)
modbin[[length(modbin) + 1]] <- update(modbin[[4]], ~ . + Number.of.vessels)
modbin[[length(modbin) + 1]] <- update(modbin[[4]], ~ . + Crew)
modbin[[length(modbin) + 1]] <- update(modbin[[4]], ~ . + HorsePower)
modbin[[length(modbin) + 1]] <- update(modbin[[4]], ~ . + FuelCapacity)
modbin[[length(modbin) + 1]] <- update(modbin[[4]], ~ . + Length)
modbin[[length(modbin) + 1]] <- update(modbin[[4]], ~ . + Fixed.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[4]], ~ . + Variable.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[4]], ~ . + sablefish)
modbin[[length(modbin) + 1]] <- update(modbin[[5]], ~ . + Number.of.vessels)
modbin[[length(modbin) + 1]] <- update(modbin[[5]], ~ . + Crew)
modbin[[length(modbin) + 1]] <- update(modbin[[5]], ~ . + Fuel)
modbin[[length(modbin) + 1]] <- update(modbin[[5]], ~ . + FuelCapacity)
modbin[[length(modbin) + 1]] <- update(modbin[[5]], ~ . + Length)
modbin[[length(modbin) + 1]] <- update(modbin[[5]], ~ . + Fixed.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[5]], ~ . + Variable.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[5]], ~ . + sablefish)
modbin[[length(modbin) + 1]] <- update(modbin[[6]], ~ . + Number.of.vessels)
modbin[[length(modbin) + 1]] <- update(modbin[[6]], ~ . + Crew)
modbin[[length(modbin) + 1]] <- update(modbin[[6]], ~ . + Fuel)
modbin[[length(modbin) + 1]] <- update(modbin[[6]], ~ . + HorsePower)
modbin[[length(modbin) + 1]] <- update(modbin[[6]], ~ . + Length)
modbin[[length(modbin) + 1]] <- update(modbin[[6]], ~ . + Fixed.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[6]], ~ . + Variable.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[6]], ~ . + sablefish)
modbin[[length(modbin) + 1]] <- update(modbin[[7]], ~ . + Number.of.vessels)
modbin[[length(modbin) + 1]] <- update(modbin[[7]], ~ . + Crew)
modbin[[length(modbin) + 1]] <- update(modbin[[7]], ~ . + Fuel)
modbin[[length(modbin) + 1]] <- update(modbin[[7]], ~ . + HorsePower)
modbin[[length(modbin) + 1]] <- update(modbin[[7]], ~ . + FuelCapacity)
modbin[[length(modbin) + 1]] <- update(modbin[[7]], ~ . + Fixed.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[7]], ~ . + Variable.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[7]], ~ . + sablefish)
modbin[[length(modbin) + 1]] <- update(modbin[[8]], ~ . + Number.of.vessels)
modbin[[length(modbin) + 1]] <- update(modbin[[8]], ~ . + Crew)
modbin[[length(modbin) + 1]] <- update(modbin[[8]], ~ . + Fuel)
modbin[[length(modbin) + 1]] <- update(modbin[[8]], ~ . + HorsePower)
modbin[[length(modbin) + 1]] <- update(modbin[[8]], ~ . + FuelCapacity)
modbin[[length(modbin) + 1]] <- update(modbin[[8]], ~ . + Length)
modbin[[length(modbin) + 1]] <- update(modbin[[8]], ~ . + Variable.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[8]], ~ . + sablefish)
modbin[[length(modbin) + 1]] <- update(modbin[[9]], ~ . + Number.of.vessels)
modbin[[length(modbin) + 1]] <- update(modbin[[9]], ~ . + Crew)
modbin[[length(modbin) + 1]] <- update(modbin[[9]], ~ . + Fuel)
modbin[[length(modbin) + 1]] <- update(modbin[[9]], ~ . + HorsePower)
modbin[[length(modbin) + 1]] <- update(modbin[[9]], ~ . + FuelCapacity)
modbin[[length(modbin) + 1]] <- update(modbin[[9]], ~ . + Length)
modbin[[length(modbin) + 1]] <- update(modbin[[9]], ~ . + Fixed.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[9]], ~ . + sablefish)
modbin[[length(modbin) + 1]] <- update(modbin[[10]], ~ . + Number.of.vessels)
modbin[[length(modbin) + 1]] <- update(modbin[[10]], ~ . + Crew)
modbin[[length(modbin) + 1]] <- update(modbin[[10]], ~ . + Fuel)
modbin[[length(modbin) + 1]] <- update(modbin[[10]], ~ . + HorsePower)
modbin[[length(modbin) + 1]] <- update(modbin[[10]], ~ . + FuelCapacity)
modbin[[length(modbin) + 1]] <- update(modbin[[10]], ~ . + Length)
modbin[[length(modbin) + 1]] <- update(modbin[[10]], ~ . + Fixed.costs)
modbin[[length(modbin) + 1]] <- update(modbin[[10]], ~ . + Variable.costs)
sink(file.path(dir.results, "binglm.txt"))
lapply(modbin, summary)
cat("\nlowest deviance model\n")
summary(modbin[[which.min(sapply(modbin, deviance))]])
sink()
bestbin <- which.min(sapply(modbin, deviance))

###############################################################################
###############################################################################
#### beta glm
###############################################################################
###############################################################################
modbeta <- list()
modbeta[[1]] <- betareg(proportion ~ portgrp, data = data.match.fixed)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[1]], ~ . + Number.of.vessels)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[1]], ~ . + Crew)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[1]], ~ . + Fuel)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[1]], ~ . + HorsePower)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[1]], ~ . + FuelCapacity)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[1]], ~ . + Length)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[1]], ~ . + Fixed.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[1]], ~ . + Variable.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[1]], ~ . + sablefish)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[2]], ~ . + Crew)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[2]], ~ . + Fuel)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[2]], ~ . + HorsePower)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[2]], ~ . + FuelCapacity)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[2]], ~ . + Length)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[2]], ~ . + Fixed.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[2]], ~ . + Variable.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[2]], ~ . + sablefish)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[3]], ~ . + Number.of.vessels)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[3]], ~ . + Fuel)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[3]], ~ . + HorsePower)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[3]], ~ . + FuelCapacity)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[3]], ~ . + Length)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[3]], ~ . + Fixed.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[3]], ~ . + Variable.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[3]], ~ . + sablefish)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[4]], ~ . + Number.of.vessels)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[4]], ~ . + Crew)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[4]], ~ . + HorsePower)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[4]], ~ . + FuelCapacity)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[4]], ~ . + Length)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[4]], ~ . + Fixed.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[4]], ~ . + Variable.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[4]], ~ . + sablefish)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[5]], ~ . + Number.of.vessels)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[5]], ~ . + Crew)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[5]], ~ . + Fuel)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[5]], ~ . + FuelCapacity)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[5]], ~ . + Length)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[5]], ~ . + Fixed.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[5]], ~ . + Variable.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[5]], ~ . + sablefish)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[6]], ~ . + Number.of.vessels)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[6]], ~ . + Crew)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[6]], ~ . + Fuel)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[6]], ~ . + HorsePower)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[6]], ~ . + Length)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[6]], ~ . + Fixed.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[6]], ~ . + Variable.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[6]], ~ . + sablefish)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[7]], ~ . + Number.of.vessels)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[7]], ~ . + Crew)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[7]], ~ . + Fuel)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[7]], ~ . + HorsePower)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[7]], ~ . + FuelCapacity)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[7]], ~ . + Fixed.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[7]], ~ . + Variable.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[7]], ~ . + sablefish)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[8]], ~ . + Number.of.vessels)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[8]], ~ . + Crew)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[8]], ~ . + Fuel)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[8]], ~ . + HorsePower)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[8]], ~ . + FuelCapacity)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[8]], ~ . + Length)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[8]], ~ . + Variable.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[8]], ~ . + sablefish)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[9]], ~ . + Number.of.vessels)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[9]], ~ . + Crew)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[9]], ~ . + Fuel)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[9]], ~ . + HorsePower)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[9]], ~ . + FuelCapacity)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[9]], ~ . + Length)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[9]], ~ . + Fixed.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[9]], ~ . + sablefish)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[10]], ~ . + Number.of.vessels)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[10]], ~ . + Crew)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[10]], ~ . + Fuel)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[10]], ~ . + HorsePower)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[10]], ~ . + FuelCapacity)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[10]], ~ . + Length)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[10]], ~ . + Fixed.costs)
modbeta[[length(modbeta) + 1]] <- update(modbeta[[10]], ~ . + Variable.costs)
sink(file.path(dir.results, "betaglm.txt"))
lapply(modbeta, summary)
cat("\nlowest AIC model\n")
summary(modbeta[[which.min(sapply(modbeta, AIC))]])
sink()
bestbeta <- which.min(sapply(modbeta, AIC))

###############################################################################
###############################################################################
#### coefficients
###############################################################################
###############################################################################
modbetares <- do.call("rbind", summary(modbeta[[bestbeta]])$coefficients)
rownames(modbetares)[1] <- levels(data.match.fixed$portgrp)[1]
rownames(modbetares) <- gsub("portgrp|\\(|\\)", "", rownames(modbetares))
modbetares <- format(modbetares, digits = 3L)
colnames(modbetares) <- c("estimate", "std error", "z value", "p value")
sink(file.path(dir.results, "glm_beta_coeff.tex"))
print(xtable(modbetares), include.rownames = TRUE,
  sanitize.text.function = function(x){x})
sink()
system(paste("pandoc", file.path(dir.results, "glm_beta_coeff.tex"), "-o",
  file.path(dir.results, "glm_beta_coeff.docx")))

#todo: may need to add in dispersion parameter
modbinres <- summary(modbin[[bestbin]])$coefficients
rownames(modbinres)[1] <- levels(data.match.fixed$portgrp)[1]
rownames(modbinres) <- gsub("portgrp|\\(|\\)", "", rownames(modbinres))
modbinres <- format(modbinres, digits = 3L)
colnames(modbinres) <- c("estimate", "std error", "t value", "p value")
sink(file.path(dir.results, "glm_bin_coeff.tex"))
print(xtable(modbinres), include.rownames = TRUE,
  sanitize.text.function = function(x){x})
sink()
system(paste("pandoc", file.path(dir.results, "glm_bin_coeff.tex"), "-o",
  file.path(dir.results, "glm_bin_coeff.docx")))

#EndOfFile
